### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by croziors** [ArhScriptEngineer/BlueprintEditor2#2]
program is corrupted by a trojan

**Comment by MoryakSPb** [comment]
VirusTotal results:
https://www.virustotal.com/gui/file/0813be2ba93dd3277bfe53e55b21cd36838bbecb8befc39a4beae4ad18b2481f/
https://www.virustotal.com/gui/file/de65698dcd59e13b5c4688a97c3275d826bfb3ee926cd4f81e1697f3a31952aa/

**Comment by ScriptedEngineer** [comment]
We working to fix that bug

**Comment by ScriptedEngineer** [comment]
FIXED
